version: "3.8"
services:
  plc:
    image: openplc/openplc:latest
    ports:
      - "8080:8080"
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
